env: "local"
graceful_shutdown_timeout: 10

http_server:
  address: "localhost:8080"
  read_timeout: 60
  write_timeout: 60
  idle_timeout: 20

postgres:
  url: "postgres://..."
  auto_migrate: false
  migrations: "./migrations/postgresql/001_initial_migrations.sql"

swag:
  endpoint: "http://localhost:8080"
  login: "admin"
  password: "admin"

logger:
  path: "logs/logger.log"

cronjob:
  kit_online_spec: "@every 10m"
  kit_online_job: false